#SPDX-License-Identifier: MIT-0
---
# tasks file for common-prep
#
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist
    autoremove: yes

- name: Install essentials
  apt:
    name:
      - python3-pip
      - curl
      - apt-transport-https
      - ca-certificates
    state: present

- name: Install Tailscale client
  shell: curl -fsSL https://tailscale.com/install.sh | sh
  args:
    creates: /usr/sbin/tailscaled

- name: Enable and start tailscaled
  systemd:
    name: tailscaled
    enabled: yes
    state: started

- name: Join Tailscale tailnet
  shell: >
    tailscale up
      --auth-key={{ ts_auth_key }}
      --hostname={{ inventory_hostname }}
      {%- if pi_role == 'plane' -%}
      --advertise-routes {{ mgmt_subnet }}
      {%- endif -%}
      --accept-routes
  args:
    creates: /var/lib/tailscale/tailscaled.state


  
