#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/k3s

- include_tasks: master.yml
  when: inventory_hostname in groups['k3s_master']

- include_tasks: agent.yml
  when: inventory_hostname in groups['k3s_workers']