all:
  children:
    k3s_master:
      hosts:
        controller01:
          ansible_host: 192.168.10.11
          pi_role: plane
    k3s_workers:
      hosts:
        controller02:
          ansible_host: 192.168.10.12
          pi_role: controller
        conteroller03:
          ansible_host: 192.168.10.13
          pi_role: controller
    pi_plane:
      children:
        k3s_master: {}
        k3s_workers: {}
  vars:
    ansible_user: ansible
    ansible_become: true

