all:
  children:
    pi_plane:
      hosts:
        controller01:
          ansible_host: 192.168.10.11
          pi_role: plane
        controller02:
          ansible_host: 192.168.10.12
          pi_role: controller
        controller03:
          ansible_host: 192.168.10.13
          pi_role: controller
  vars:
    ansible_user: ansible
    ansible_become: true

