---
- name: Add GitHub Actions runner key to ansible user
  hosts: pi_plane
  remote_user: atshi
  become: true
  vars:
    gh_runner_pub: "{{ lookup('file', lookup('env','HOME') + '/.ssh/github_actions.pub') }}"
  tasks:
    - name: Ensure .ssh exists for ansible
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Install CI public key
      authorized_key:
        user: ansible
        key: "{{ gh_runner_pub }}"
        state: present

