---
- name: Phase 0 - Install Docker & Tailscale
  hosts: pi_plane
  roles:
    - bootstrap-user
    - common-prep

- name: Phase 0 - add flux ssh key
  hosts: k3s_master
  roles:
    - flux-prep
    

