name: Phase0 Bootstrap
on: [push]

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Tailscale & Join Tailnet
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up \
            --authkey=${{ secrets.TS_AUTH_KEY }} \
            --hostname=ci-runner \
            --accept-routes

      - name: Install Ansible & Dependencies
        run: |
          sudo apt update && sudo apt install -y docker.io python3-pip gnupg
          pip3 install ansible ansible-sops docker-compose

      - name: Run Phase0 Playbook
        run: |
          ansible-playbook \
            -i ansible/inventories/hosts.yml \
            ansible/playbooks/phase0.yml

